### ISSUE TITLE
Give a more descriptive error message when config file is missing

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/iShovel#3]
If a user has not generated a  config file, error he currently sees is:
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from utils import get_user_data, update_scorecard, get_normalised_scorecard
  File "/home/prabhakar/Dev/iShovel/utils.py", line 13, in <module>
    master_username = config.get("Github", "username")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Github'
```

We should be giving a more descriptive error and maybe create a default config for him

**Comment by chaintng** [comment]
i can do it.

**Comment by chaintng** [comment]
done kub https://github.com/prabhakar267/iShovel/pull/4
